# Tools Pipeline - Simplified (Terraform Only)
# Terraform handles all tool installations (NGINX, ArgoCD, SonarQube, ALB Controller)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - terraform/tools/*

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: devops-config
  - name: TF_VAR_aws_region
    value: "us-east-1"
  - name: TF_VAR_project_name
    value: "devops-final"
  - name: S3_BUCKET_NAME
    value: "backend-s3-final-project"
  - name: VAULT_ADDRESS
    value: "http://18.215.161.128:8200"
  - name: NEXUS_URL
    value: "http://18.215.161.128:8081"
  - name: GIT_REPO_URL
    value: "https://github.com/ahmedekramalsada/final-project-devops.git"

stages:
  - stage: DeployTools
    displayName: "Deploy Tools Infrastructure"
    jobs:
      - job: DeployTools
        displayName: "Deploy Tools"
        steps:
          # Step 1: Install Terraform
          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: "1.5.7"

          # Step 2: Initialize Terraform with S3 Backend
          - task: TerraformTaskV4@4
            displayName: "Terraform Init"
            inputs:
              provider: "aws"
              command: "init"
              workingDirectory: "$(System.DefaultWorkingDirectory)/terraform/tools"
              backendServiceAWS: "aws-terraform-connection"
              backendAWSBucketName: "$(S3_BUCKET_NAME)"
              backendAWSKey: "tools/terraform.tfstate"
              backendAWSRegion: "us-east-1"

          # Step 3: Terraform Validate
          - task: TerraformTaskV4@4
            displayName: "Terraform Validate"
            inputs:
              provider: "aws"
              command: "validate"
              workingDirectory: "$(System.DefaultWorkingDirectory)/terraform/tools"

          # Step 4: Terraform Plan
          - task: TerraformTaskV4@4
            displayName: "Terraform Plan"
            inputs:
              provider: "aws"
              command: "plan"
              workingDirectory: "$(System.DefaultWorkingDirectory)/terraform/tools"
              commandOptions: >
                -var="aws_region=$(TF_VAR_aws_region)"
                -var="project_name=$(TF_VAR_project_name)"
                -var="vault_address=$(VAULT_ADDRESS)"
                -var="vault_token=$(vault-token)"
                -var="nexus_url=$(NEXUS_URL)"
                -var="git_repo_url=$(GIT_REPO_URL)"
                -out=tfplan
              environmentServiceNameAWS: "aws-terraform-connection"

          # Step 5: Terraform Apply
          - task: TerraformTaskV4@4
            displayName: "Terraform Apply"
            inputs:
              provider: "aws"
              command: "apply"
              workingDirectory: "$(System.DefaultWorkingDirectory)/terraform/tools"
              commandOptions: "tfplan"
              environmentServiceNameAWS: "aws-terraform-connection"

          # Step 6: Terraform Output
          - task: TerraformTaskV4@4
            displayName: "Terraform Output"
            inputs:
              provider: "aws"
              command: "custom"
              customCommand: "output"
              workingDirectory: "$(System.DefaultWorkingDirectory)/terraform/tools"
              environmentServiceNameAWS: "aws-terraform-connection"
