# Tools Pipeline - Deploys NGINX, ArgoCD, SonarQube
# Terraform handles all tool installations

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - terraform/tools/*

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: devops-config
  - name: TF_VAR_aws_region
    value: "us-east-1"
  - name: TF_VAR_project_name
    value: "devops-final"
  - name: S3_BUCKET_NAME
    value: "backend-s3-final-project"
  - name: VAULT_ADDRESS
    value: "http://18.215.161.128:8200"
  - name: NEXUS_URL
    value: "http://18.215.161.128:8081"
  - name: GIT_REPO_URL
    value: "https://github.com/ahmedekramalsada/final-project-devops.git"

stages:
  - stage: DeployTools
    displayName: "Deploy Tools Infrastructure"
    jobs:
      - job: DeployTools
        displayName: "Deploy Tools"
        timeoutInMinutes: 90
        steps:
          # Step 0: Install AWS CLI and cleanup existing IAM resources
          - task: AwsCli@1
            displayName: "Cleanup IAM Resources"
            inputs:
              awsCredentials: "aws-terraform-connection"
              regionName: "us-east-1"
              scriptType: "bash"
              scriptInline: |
                echo "Cleaning up existing IAM resources..."
                ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
                POLICY_ARN="arn:aws:iam::${ACCOUNT_ID}:policy/devops-final-lb-controller"
                ROLE_NAME="devops-final-lb-controller"

                echo "Account ID: ${ACCOUNT_ID}"
                echo "Policy ARN: ${POLICY_ARN}"
                echo "Role Name: ${ROLE_NAME}"

                # List and detach all policies from role
                echo "Listing attached policies..."
                aws iam list-attached-role-policies --role-name ${ROLE_NAME} 2>/dev/null || echo "Role not found"

                # Detach the specific policy
                echo "Detaching policy from role..."
                aws iam detach-role-policy --role-name ${ROLE_NAME} --policy-arn ${POLICY_ARN} 2>/dev/null || echo "Policy not attached or already detached"

                # Wait a moment for detachment to complete
                sleep 5

                # Delete role
                echo "Deleting role: ${ROLE_NAME}"
                aws iam delete-role --role-name ${ROLE_NAME} 2>/dev/null || echo "Role not found or already deleted"

                # Delete policy
                echo "Deleting policy: ${POLICY_ARN}"
                aws iam delete-policy --policy-arn ${POLICY_ARN} 2>/dev/null || echo "Policy not found or already deleted"

                echo "Cleanup complete!"

          # Step 1: Install Terraform
          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: "1.5.7"

          # Step 2: Initialize Terraform with S3 Backend
          - task: TerraformTaskV4@4
            displayName: "Terraform Init"
            inputs:
              provider: "aws"
              command: "init"
              workingDirectory: "$(System.DefaultWorkingDirectory)/terraform/tools"
              backendServiceAWS: "aws-terraform-connection"
              backendAWSBucketName: "$(S3_BUCKET_NAME)"
              backendAWSKey: "tools/terraform.tfstate"
              backendAWSRegion: "us-east-1"

          # Step 3: Terraform Validate
          - task: TerraformTaskV4@4
            displayName: "Terraform Validate"
            inputs:
              provider: "aws"
              command: "validate"
              workingDirectory: "$(System.DefaultWorkingDirectory)/terraform/tools"

          # Step 4: Terraform Plan
          - task: TerraformTaskV4@4
            displayName: "Terraform Plan"
            inputs:
              provider: "aws"
              command: "plan"
              workingDirectory: "$(System.DefaultWorkingDirectory)/terraform/tools"
              commandOptions: >
                -var="aws_region=$(TF_VAR_aws_region)"
                -var="project_name=$(TF_VAR_project_name)"
                -var="vault_address=$(VAULT_ADDRESS)"
                -var="vault_token=$(vault-token)"
                -var="nexus_url=$(NEXUS_URL)"
                -var="git_repo_url=$(GIT_REPO_URL)"
                -out=tfplan
              environmentServiceNameAWS: "aws-terraform-connection"

          # Step 5: Terraform Apply
          - task: TerraformTaskV4@4
            displayName: "Terraform Apply"
            inputs:
              provider: "aws"
              command: "apply"
              workingDirectory: "$(System.DefaultWorkingDirectory)/terraform/tools"
              commandOptions: "tfplan"
              environmentServiceNameAWS: "aws-terraform-connection"

          # Step 6: Terraform Output
          - task: TerraformTaskV4@4
            displayName: "Terraform Output"
            inputs:
              provider: "aws"
              command: "custom"
              customCommand: "output"
              workingDirectory: "$(System.DefaultWorkingDirectory)/terraform/tools"
              environmentServiceNameAWS: "aws-terraform-connection"

          # Step 7: Check pod status
          - script: |
              echo "Checking SonarQube pod status..."
              kubectl get pods -n tooling || true
              echo ""
              echo "Checking all namespaces..."
              kubectl get pods -A || true
            displayName: "Check Pod Status"
            condition: always()
