# =============================================================================
# Tools Pipeline - Deploys NGINX, ArgoCD, SonarQube
# Terraform handles all tool installations with proper IRSA configuration
# =============================================================================

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - terraform/tools/*

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: devops-config
  - name: TF_VAR_aws_region
    value: "us-east-1"
  - name: TF_VAR_project_name
    value: "devops-final"
  - name: S3_BUCKET_NAME
    value: "backend-s3-final-project"
  - name: VAULT_ADDRESS
    value: "http://18.215.161.128:8200"
  - name: NEXUS_URL
    value: "http://18.215.161.128:8081"
  - name: GIT_REPO_URL
    value: "https://github.com/ahmedekramalsada/final-project-devops.git"

stages:
  - stage: DeployTools
    displayName: "Deploy Tools Infrastructure"
    jobs:
      - job: DeployTools
        displayName: "Deploy Tools"
        timeoutInMinutes: 120
        steps:
          # Step 1: Install kubectl
          - script: |
              echo "Installing kubectl..."
              curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
              chmod +x kubectl
              sudo mv kubectl /usr/local/bin/
              kubectl version --client --output yaml
            displayName: "Install kubectl"

          # Step 2: Install Terraform
          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: "1.5.7"

          # Step 3: Initialize Terraform with S3 Backend
          - task: TerraformTaskV4@4
            displayName: "Terraform Init"
            inputs:
              provider: "aws"
              command: "init"
              workingDirectory: "$(System.DefaultWorkingDirectory)/terraform/tools"
              backendServiceAWS: "aws-terraform-connection"
              backendAWSBucketName: "$(S3_BUCKET_NAME)"
              backendAWSKey: "tools/terraform.tfstate"
              backendAWSRegion: "us-east-1"

          # Step 4: Configure kubectl
          - script: |
              aws eks update-kubeconfig --name devops-cluster --region us-east-1
              kubectl cluster-info
            displayName: "Configure kubectl"
            env:
              AWS_ACCESS_KEY_ID: $(aws-access-key-id)
              AWS_SECRET_ACCESS_KEY: $(aws-secret-access-key)
              AWS_DEFAULT_REGION: "us-east-1"

          # Step 5: Import existing Kubernetes resources to Terraform state
          # This MUST happen BEFORE terraform plan
          - script: |
              cd "$(System.DefaultWorkingDirectory)/terraform/tools"

              echo "=== Checking for existing resources ==="

              # Import service account if it exists
              if kubectl get serviceaccount aws-load-balancer-controller -n kube-system >/dev/null 2>&1; then
                echo "Service account exists, importing to Terraform state..."
                terraform import -lock=false kubernetes_service_account.lb_controller kube-system/aws-load-balancer-controller 2>/dev/null || echo "Already in state or import failed, continuing..."
              else
                echo "Service account does not exist, will be created by Terraform"
              fi

              # Import nexus registry secret if it exists
              if kubectl get secret nexus-registry-secret -n default >/dev/null 2>&1; then
                echo "Nexus secret exists, importing to Terraform state..."
                terraform import -lock=false kubernetes_secret.nexus_registry default/nexus-registry-secret 2>/dev/null || echo "Already in state or import failed, continuing..."
              fi

              echo "=== Import complete ==="
            displayName: "Import Existing Resources"
            env:
              AWS_ACCESS_KEY_ID: $(aws-access-key-id)
              AWS_SECRET_ACCESS_KEY: $(aws-secret-access-key)
              AWS_DEFAULT_REGION: "us-east-1"

          # Step 6: Terraform Validate
          - task: TerraformTaskV4@4
            displayName: "Terraform Validate"
            inputs:
              provider: "aws"
              command: "validate"
              workingDirectory: "$(System.DefaultWorkingDirectory)/terraform/tools"

          # Step 7: Terraform Plan (AFTER imports)
          - task: TerraformTaskV4@4
            displayName: "Terraform Plan"
            inputs:
              provider: "aws"
              command: "plan"
              workingDirectory: "$(System.DefaultWorkingDirectory)/terraform/tools"
              commandOptions: >
                -var="aws_region=$(TF_VAR_aws_region)"
                -var="project_name=$(TF_VAR_project_name)"
                -var="vault_address=$(VAULT_ADDRESS)"
                -var="vault_token=$(vault-token)"
                -var="nexus_url=$(NEXUS_URL)"
                -var="git_repo_url=$(GIT_REPO_URL)"
                -out=tfplan
              environmentServiceNameAWS: "aws-terraform-connection"

          # Step 8: Terraform Apply
          - task: TerraformTaskV4@4
            displayName: "Terraform Apply"
            inputs:
              provider: "aws"
              command: "apply"
              workingDirectory: "$(System.DefaultWorkingDirectory)/terraform/tools"
              commandOptions: "tfplan"
              environmentServiceNameAWS: "aws-terraform-connection"

          # Step 9: Verify deployment
          - script: |
              echo "=== Verifying AWS Load Balancer Controller ==="
              kubectl get pods -n kube-system -l app.kubernetes.io/name=aws-load-balancer-controller || echo "LB Controller pods not yet ready"
              echo ""
              echo "=== Checking Service Account Annotation ==="
              kubectl get serviceaccount aws-load-balancer-controller -n kube-system -o jsonpath='{.metadata.annotations.eks\.amazonaws\.com/role-arn}' && echo "" || echo "SA not found"
            displayName: "Verify Deployment"
            env:
              AWS_ACCESS_KEY_ID: $(aws-access-key-id)
              AWS_SECRET_ACCESS_KEY: $(aws-secret-access-key)
              AWS_DEFAULT_REGION: "us-east-1"

          # Step 10: Check all pod status
          - script: |
              echo "=== All Pods Status ==="
              kubectl get pods -A || true
            displayName: "Check Pod Status"
            env:
              AWS_ACCESS_KEY_ID: $(aws-access-key-id)
              AWS_SECRET_ACCESS_KEY: $(aws-secret-access-key)
              AWS_DEFAULT_REGION: "us-east-1"
            condition: always()

          # Step 11: Terraform Output
          - task: TerraformTaskV4@4
            displayName: "Terraform Output"
            inputs:
              provider: "aws"
              command: "custom"
              customCommand: "output"
              workingDirectory: "$(System.DefaultWorkingDirectory)/terraform/tools"
              environmentServiceNameAWS: "aws-terraform-connection"
